apiVersion: v1
kind: Service
metadata:
  name: opsprobe
  namespace: default
  labels:
    app.kubernetes.io/name: opsprobe
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opsprobe
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
