<#
.SYNOPSIS
    foundation_probe.ps1 - Automated evidence generator for Go compiler, assembly, escape analysis, and runtime internals.

.DESCRIPTION
    Provides reproducible compilation and disassembly evidence for the foundation chapters of the book.
    All evidence artifacts include strict metadata headers (Go version, GOOS, GOARCH, UTC timestamp, exact command).

.PARAMETER Mode
    One of: SourceToAsm, Objdump, Escape, Optimizations, BuildInfo.

.PARAMETER SourceFile
    Path to the Go source file or package under inspection.

.PARAMETER Symbol
    Optional symbol/function name filter for Objdump or disassembly.

.PARAMETER OutDir
    Target directory for evidence outputs. Defaults to .workspace/foundation-evidence.

.PARAMETER Force
    Overwrite existing evidence files if present.

.PARAMETER Verbosity
    Verbosity level (1 or 2). For Escape mode: 1 = -m, 2 = -m -m.
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory = $true, Position = 0)]
    [ValidateSet("SourceToAsm", "Objdump", "Escape", "Optimizations", "BuildInfo")]
    [string]$Mode,

    [Parameter(Mandatory = $false, Position = 1)]
    [string]$SourceFile,

    [Parameter(Mandatory = $false)]
    [string]$Symbol,

    [Parameter(Mandatory = $false)]
    [string]$OutDir,

    [Parameter(Mandatory = $false)]
    [switch]$Force,

    [Parameter(Mandatory = $false)]
    [int]$Verbosity = 1
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# 1. Resolve Go toolchain
$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$LocalGo = Join-Path $ProjectRoot ".tools\go1.27.1\bin\go.exe"
if (Test-Path $LocalGo) {
    $GoExe = $LocalGo
} else {
    $GoExe = (Get-Command go -ErrorAction SilentlyContinue).Source
    if (-not $GoExe) {
        Write-Error "Go executable not found in .tools/go1.27.1/bin/go.exe or system PATH."
        exit 1
    }
}

# 2. Query environment
$GoVer = (& $GoExe version).Trim()
$GoOs = (& $GoExe env GOOS).Trim()
$GoArch = (& $GoExe env GOARCH).Trim()
$GoRoot = (& $GoExe env GOROOT).Trim()
$UtcTimestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

# 3. Resolve OutDir
if (-not $OutDir) {
    $OutDir = Join-Path $ProjectRoot ".workspace\foundation-evidence"
}
if (-not (Test-Path $OutDir)) {
    New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
}

$ScratchDir = Join-Path $ProjectRoot ".workspace\scratch"
if (-not (Test-Path $ScratchDir)) {
    New-Item -ItemType Directory -Path $ScratchDir -Force | Out-Null
}

function Write-MetadataHeader {
    param (
        [string]$EvidenceKind,
        [string]$CommandExecuted,
        [string]$TargetSource,
        [string]$Notes
    )

    $header = @"
================================================================================
EVIDENCE METADATA HEADER
================================================================================
EVIDENCE_KIND    : $EvidenceKind
UTC_TIMESTAMP    : $UtcTimestamp
GO_VERSION       : $GoVer
TARGET_OS/ARCH   : $GoOs/$GoArch
GOROOT           : $GoRoot
SOURCE_FILE      : $TargetSource
COMMAND_EXECUTED : $CommandExecuted
================================================================================
DISAMBIGUATION NOTE:
$Notes
================================================================================

"@
    return $header
}

switch ($Mode) {
    "BuildInfo" {
        $outFile = Join-Path $OutDir "build_info_${GoOs}_${GoArch}.txt"
        if ((Test-Path $outFile) -and (-not $Force)) {
            Write-Warning "File $outFile already exists. Use -Force to overwrite."
            return
        }

        $cmdStr = "$GoExe env"
        $notes = "Reports build environment, toolchain paths, and host/target configuration."
        $header = Write-MetadataHeader -EvidenceKind "TOOLCHAIN_BUILD_INFO" -CommandExecuted $cmdStr -TargetSource "N/A" -Notes $notes
        $envOutput = & $GoExe env
        $content = $header + ($envOutput -join "`n")
        Set-Content -Path $outFile -Value $content -Encoding utf8
        Write-Host "Generated build info evidence: $outFile"
    }

    "SourceToAsm" {
        if (-not $SourceFile) {
            Write-Error "SourceFile parameter is required for SourceToAsm mode."
            exit 1
        }
        $resolvedSource = (Resolve-Path $SourceFile).Path
        $baseName = [System.IO.Path]::GetFileNameWithoutExtension($resolvedSource)
        $outFile = Join-Path $OutDir "${baseName}_compiler_S_${GoArch}.asm"

        if ((Test-Path $outFile) -and (-not $Force)) {
            Write-Warning "File $outFile already exists. Use -Force to overwrite."
            return
        }

        $sourceDir = [System.IO.Path]::GetDirectoryName($resolvedSource)
        $fileName = [System.IO.Path]::GetFileName($resolvedSource)
        $cmdStr = "$GoExe build -gcflags=`"-S`" -o NUL $fileName (in $sourceDir)"
        $notes = "COMPILER ASSEMBLY LISTING (-S): This output is generated by the compiler's ssagen backend.`nIt represents intermediate pseudo-assembly instructions with virtual registers and runtime pseudo-ops,`nNOT the final linked machine binary machine code."
        $header = Write-MetadataHeader -EvidenceKind "COMPILER_ASSEMBLY_LISTING" -CommandExecuted $cmdStr -TargetSource $resolvedSource -Notes $notes

        $stdoutFile = Join-Path $ScratchDir "temp_asm.stdout"
        $stderrFile = Join-Path $ScratchDir "temp_asm.stderr"
        if (Test-Path $stdoutFile) { Remove-Item $stdoutFile -Force }
        if (Test-Path $stderrFile) { Remove-Item $stderrFile -Force }

        $proc = Start-Process -FilePath $GoExe -ArgumentList "build", "-gcflags=-S", "-o", "NUL", "`"$fileName`"" -WorkingDirectory $sourceDir -NoNewWindow -PassThru -RedirectStandardOutput $stdoutFile -RedirectStandardError $stderrFile
        $proc.WaitForExit()

        $stdout = if (Test-Path $stdoutFile) { Get-Content $stdoutFile -Raw } else { "" }
        $stderr = if (Test-Path $stderrFile) { Get-Content $stderrFile -Raw } else { "" }

        # go build -gcflags="-S" prints assembly listing to stderr
        $asmBody = if ($stderr.Trim().Length -gt 0) { $stderr } else { $stdout }
        $fullOutput = $header + $asmBody
        Set-Content -Path $outFile -Value $fullOutput -Encoding utf8
        Write-Host "Generated SourceToAsm evidence: $outFile"
    }

    "Objdump" {
        if (-not $SourceFile) {
            Write-Error "SourceFile parameter is required for Objdump mode."
            exit 1
        }
        $resolvedSource = (Resolve-Path $SourceFile).Path
        $baseName = [System.IO.Path]::GetFileNameWithoutExtension($resolvedSource)
        $tempExe = Join-Path $ScratchDir "${baseName}_probe.exe"
        $outFile = Join-Path $OutDir "${baseName}_objdump_${GoArch}.txt"

        if ((Test-Path $outFile) -and (-not $Force)) {
            Write-Warning "File $outFile already exists. Use -Force to overwrite."
            return
        }

        # Build binary
        & $GoExe build -o $tempExe $resolvedSource
        if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to build binary for objdump from $resolvedSource"
            exit $LASTEXITCODE
        }

        $objdumpArgs = @("tool", "objdump")
        if ($Symbol) {
            $objdumpArgs += "-s", $Symbol
        }
        $objdumpArgs += $tempExe

        $cmdStr = "$GoExe " + ($objdumpArgs -join " ")
        $notes = "MACHINE BINARY DISASSEMBLY (go tool objdump): This output disassembles executable machine instructions`nfrom the linked binary. Addresses and machine opcodes correspond to concrete target architecture instructions."
        $header = Write-MetadataHeader -EvidenceKind "BINARY_MACHINE_OBJDUMP" -CommandExecuted $cmdStr -TargetSource $resolvedSource -Notes $notes

        $proc = Start-Process -FilePath $GoExe -ArgumentList $objdumpArgs -NoNewWindow -PassThru -RedirectStandardOutput (Join-Path $ScratchDir "temp_objdump.stdout") -RedirectStandardError (Join-Path $ScratchDir "temp_objdump.stderr")
        $proc.WaitForExit()

        $stdout = if (Test-Path (Join-Path $ScratchDir "temp_objdump.stdout")) { Get-Content (Join-Path $ScratchDir "temp_objdump.stdout") -Raw } else { "" }
        $fullOutput = $header + $stdout
        Set-Content -Path $outFile -Value $fullOutput -Encoding utf8
        Write-Host "Generated Objdump evidence: $outFile"
    }

    "Escape" {
        if (-not $SourceFile) {
            Write-Error "SourceFile parameter is required for Escape mode."
            exit 1
        }
        $resolvedSource = (Resolve-Path $SourceFile).Path
        $baseName = [System.IO.Path]::GetFileNameWithoutExtension($resolvedSource)
        $mFlag = if ($Verbosity -ge 2) { "-m -m" } else { "-m" }
        $outFile = Join-Path $OutDir "${baseName}_escape_analysis.txt"

        if ((Test-Path $outFile) -and (-not $Force)) {
            Write-Warning "File $outFile already exists. Use -Force to overwrite."
            return
        }

        $cmdStr = "$GoExe build -gcflags=`"$mFlag`" -o NUL $resolvedSource"
        $notes = "ESCAPE ANALYSIS (-gcflags=`"$mFlag`"): Reports compiler escape decisions (stack allocation vs heap escaping),`nparameter flow, and closure capture diagnostics."
        $header = Write-MetadataHeader -EvidenceKind "COMPILER_ESCAPE_ANALYSIS" -CommandExecuted $cmdStr -TargetSource $resolvedSource -Notes $notes

        $proc = Start-Process -FilePath $GoExe -ArgumentList "build", "-gcflags=$mFlag", "-o", "NUL", "`"$resolvedSource`"" -NoNewWindow -PassThru -RedirectStandardOutput (Join-Path $ScratchDir "temp_escape.stdout") -RedirectStandardError (Join-Path $ScratchDir "temp_escape.stderr")
        $proc.WaitForExit()

        $stdout = if (Test-Path (Join-Path $ScratchDir "temp_escape.stdout")) { Get-Content (Join-Path $ScratchDir "temp_escape.stdout") -Raw } else { "" }
        $stderr = if (Test-Path (Join-Path $ScratchDir "temp_escape.stderr")) { Get-Content (Join-Path $ScratchDir "temp_escape.stderr") -Raw } else { "" }
        $body = $stdout + "`n" + $stderr

        $fullOutput = $header + $body.Trim()
        Set-Content -Path $outFile -Value $fullOutput -Encoding utf8
        Write-Host "Generated Escape Analysis evidence: $outFile"
    }

    "Optimizations" {
        if (-not $SourceFile) {
            Write-Error "SourceFile parameter is required for Optimizations mode."
            exit 1
        }
        $resolvedSource = (Resolve-Path $SourceFile).Path
        $baseName = [System.IO.Path]::GetFileNameWithoutExtension($resolvedSource)
        $outFile = Join-Path $OutDir "${baseName}_ssa_optimizations.txt"

        if ((Test-Path $outFile) -and (-not $Force)) {
            Write-Warning "File $outFile already exists. Use -Force to overwrite."
            return
        }

        # Inlining and SSA prove (bounds check elimination) flags
        $gcflags = "-m -d=ssa/prove/debug=1"
        $cmdStr = "$GoExe build -gcflags=`"$gcflags`" -o NUL $resolvedSource"
        $notes = "SSA OPTIMIZATIONS & BOUNDS CHECK ELIMINATION: Reports inlining decisions and SSA prove pass diagnostic logs`nshowing proven bounds and eliminated runtime panic checks."
        $header = Write-MetadataHeader -EvidenceKind "SSA_OPTIMIZATIONS_PROVE" -CommandExecuted $cmdStr -TargetSource $resolvedSource -Notes $notes

        $proc = Start-Process -FilePath $GoExe -ArgumentList "build", "-gcflags=$gcflags", "-o", "NUL", "`"$resolvedSource`"" -NoNewWindow -PassThru -RedirectStandardOutput (Join-Path $ScratchDir "temp_opt.stdout") -RedirectStandardError (Join-Path $ScratchDir "temp_opt.stderr")
        $proc.WaitForExit()

        $stdout = if (Test-Path (Join-Path $ScratchDir "temp_opt.stdout")) { Get-Content (Join-Path $ScratchDir "temp_opt.stdout") -Raw } else { "" }
        $stderr = if (Test-Path (Join-Path $ScratchDir "temp_opt.stderr")) { Get-Content (Join-Path $ScratchDir "temp_opt.stderr") -Raw } else { "" }
        $body = $stdout + "`n" + $stderr

        $fullOutput = $header + $body.Trim()
        Set-Content -Path $outFile -Value $fullOutput -Encoding utf8
        Write-Host "Generated SSA Optimizations evidence: $outFile"
    }
}
